# Generated by Django 4.2.1 on 2024-05-19 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0003_remove_contact_created_at_contact_updated_on"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="updated_on",
        ),
        migrations.AddField(
            model_name="contact",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
