# Generated by Django 4.2.1 on 2024-05-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0004_remove_contact_updated_on_contact_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="created_at",
        ),
        migrations.AddField(
            model_name="contact",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
