# Generated by Django 4.2.1 on 2024-06-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="date_joined",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="full_name",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
